# Generated by Django 4.2 on 2023-04-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='a',
            field=models.IntegerField(verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='b',
            field=models.IntegerField(verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='c',
            field=models.IntegerField(verbose_name='c'),
        ),
    ]
