# Generated by Django 4.2 on 2023-04-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.BigIntegerField(verbose_name='telefone'),
        ),
    ]
